from taquin import Taquin


t:Taquin = Taquin(3,None)
t.remplir()
t2=t.clone()
t3=t.clone()
t4=t3.clone()
t5=t4.clone()
print(t.__str__())
print(t2.__str__())
print(t3.__str__())
print(t4.__str__())
print(t5.__str__())
t.shuffle(1000)
print(t.__str__())
print(t2.__str__())
print(t3.__str__())
print(t4.__str__())
print(t5.__str__())
t3=t.clone()
print(t.__str__())
print(t2.__str__())
print(t3.__str__())
print(t4.__str__())
print(t5.__str__())
t3.shuffle(1000)

t.shuffle(1000)
t.shuffle(1000)
t2=t2.clone()
print(t.__str__())
print(t2.__str__())
print(t3.__str__())
print(t4.__str__())
print(t5.__str__())
for i in range(1000):
    t=t.clone()
print(t.__str__())
print(t2.__str__())
print(t3.__str__())
print(t4.__str__())
print(t5.__str__())
for i in range(1000):
    t=t.clone()
print(t.__str__())
print(t2.__str__())
print(t3.__str__())
print(t4.__str__())
print(t5.__str__())

print("_________________________________________________________")
t=Taquin(3,None)
t.remplir()
t=t.move("W")
print(t.__str__())
t=t.move("W")
print(t.__str__())
t=t.move("N")
print(t.__str__())
t=t.move("N")
print(t.__str__())
t=t.move("E")
print(t.__str__())
t=t.move("E")
print(t.__str__())
t=t.move("S")
print(t.__str__())
t=t.move("S")
print(t.__str__())
print(t.__str__())